tddDjango/tddDjango/urls.py
from django.contrib import admin
from django.urls import path
from hashing import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('hash/<str:hash>', views.hash_func, name='hash'),
    path('quickhash', views.quickhash, name='quickhash')
]

tddDjango/hashing/models.py
from django.db import models


# Create your models here.
class Hash(models.Model):
    text = models.TextField()
    hash = models.CharField(max_length=64)

tddDjango/hashing/forms.py
from django import forms


class HashForm(forms.Form):
    text = forms.CharField(label='Enter hash here:', widget=forms.Textarea)

tddDjango/hashing/views.py
from django.shortcuts import render, redirect
from .forms import HashForm
from .models import Hash
import hashlib
from django.http import JsonResponse


# Create your views here.
def home(request):
    if request.method == 'POST':
        filled_form = HashForm(request.POST)

        if filled_form.is_valid():
            text = filled_form.cleaned_data['text']
            text_hash = hashlib.sha256(text.encode('utf-8')).hexdigest()
            try:
                Hash.objects.get(hash=text_hash)
            except Hash.DoesNotExist:
                hash = Hash()
                hash.text = text
                hash.hash = text_hash
                hash.save()

            return redirect('hash', hash=text_hash)

    form = HashForm()
    return render(request, 'hashing/home.html', {'form': form})


def hash_func(request, hash):
    hash_obj = Hash.objects.get(hash=hash)
    return render(request, 'hashing/hash.html', {'hash': hash_obj})


def quickhash(request):
    text = request.GET('text')
    return JsonResponse({'hash': hashlib.sha256(text.encode('utf-8')).hexdigest()})

tddDjango/hashing/templates/hashing/hash.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hash view</title>
</head>
<body>
<h2>Hash:</h2>
<h1>{{  hash.hash }}</h1>
<h2>Text:</h2>
{{ hash.text }}

<a href="{% url 'home' %}">Home</a>
</body>
</html>

tddDjango/hashing/templates/hashing/home.html
<head>
    <title>Home hash function</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>

<form action="{% url 'home' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="button" value="Hash">
</form>

<h2 id="quickhash"></h2>

<script>
    $('#id_text').keyup(function () {
        let text = $(this).val();

        $.ajax({
            url: '/quickhash',
            data: {
                'text': text
            },
            dataType: 'json',
        }).done(function (data) {
            $('#quickhash').text(data['hash']);
        }).fail(function () {
            alert('Error retrieving hash text');
        })
    });
</script>